# Generated by Django 3.2 on 2021-05-06 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('block_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blocked_domain',
            },
        ),
        migrations.CreateModel(
            name='UserUrlStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_url_status',
            },
        ),
        migrations.CreateModel(
            name='UserUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.CharField(max_length=2000)),
                ('user_url_hash', models.CharField(default='', max_length=32)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('resolve_path', models.CharField(max_length=12, null=True)),
                ('resolve_host', models.CharField(max_length=16, null=True)),
                ('user_domain', models.CharField(blank=True, max_length=100)),
                ('block_reason', models.CharField(blank=True, max_length=120, null=True)),
                ('block_date', models.DateTimeField(blank=True, null=True, verbose_name='date blocked')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='urlshortener.userurlstatus')),
            ],
            options={
                'db_table': 'user_url',
            },
        ),
        migrations.AddIndex(
            model_name='blockeddomain',
            index=models.Index(fields=['domain'], name='blocked_dom_domain_6acb56_idx'),
        ),
        migrations.AddIndex(
            model_name='userurl',
            index=models.Index(fields=['resolve_host'], name='user_url_resolve_b89f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='userurl',
            index=models.Index(fields=['user_domain', 'status'], name='user_url_user_do_6171b4_idx'),
        ),
        migrations.AddIndex(
            model_name='userurl',
            index=models.Index(fields=['user_url_hash'], name='user_url_user_ur_271fda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userurl',
            unique_together={('resolve_path', 'resolve_host')},
        ),
    ]
