# Generated by Django 3.2 on 2021-05-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurl',
            name='user_url_hash',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userurl',
            name='block_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date blocked'),
        ),
        migrations.AlterField(
            model_name='userurl',
            name='block_reason',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userurl',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='userurl',
            name='user_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
