# Generated by Django 3.2 on 2021-05-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20210506_1842'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userurl',
            index=models.Index(fields=['user_url_hash'], name='user_url_user_ur_271fda_idx'),
        ),
    ]
