# Generated by Django 3.2 on 2021-05-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_userurl_user_url_user_ur_271fda_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blockeddomain',
            index=models.Index(fields=['domain'], name='blocked_dom_domain_6acb56_idx'),
        ),
    ]
