# Generated by Django 3.2 on 2021-05-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_blockeddomain_blocked_dom_domain_6acb56_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeddomain',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
